#define GPIODIR_A_APB_BASE 0X400040000
#define GPIODIR_A_AHB_BASE 0X400580000
#define GPIODIR_B_APB_BASE 0X400050000
#define GPIODIR_B_AHB_BASE 0X400590000
#define GPIODIR_C_APB_BASE 0X400060000
#define GPIODIR_C_AHB_BASE 0X4005A0000
#define GPIODIR_D_APB_BASE 0X400070000
#define GPIODIR_D_AHB_BASE 0X4005B0000
#define GPIODIR_E_APB_BASE 0X400240000
#define GPIODIR_E_AHB_BASE 0X4005C0000
#define GPIODIR_F_APB_BASE 0X400250000
#define GPIODIR_F_AHB_BASE 0X4005D0000

#define GPIODIR_OFFSET 0X400

#define GPIODIR_A_APB *(volatile uint32_t *)(GPIODIR_A_APB_BASE+GPIODIR_OFFSET)
#define GPIODIR_A_AHB *(volatile uint32_t *)(GPIODIR_A_AHB_BASE+GPIODIR_OFFSET)
#define GPIODIR_B_APB *(volatile uint32_t *)(GPIODIR_B_APB_BASE+GPIODIR_OFFSET)
#define GPIODIR_B_AHB *(volatile uint32_t *)(GPIODIR_B_AHB_BASE+GPIODIR_OFFSET)
#define GPIODIR_C_APB *(volatile uint32_t *)(GPIODIR_C_APB_BASE+GPIODIR_OFFSET)
#define GPIODIR_C_AHB *(volatile uint32_t *)(GPIODIR_C_AHB_BASE+GPIODIR_OFFSET)
#define GPIODIR_D_APB *(volatile uint32_t *)(GPIODIR_D_APB_BASE+GPIODIR_OFFSET)
#define GPIODIR_D_AHB *(volatile uint32_t *)(GPIODIR_D_AHB_BASE+GPIODIR_OFFSET)
#define GPIODIR_E_APB *(volatile uint32_t *)(GPIODIR_E_APB_BASE+GPIODIR_OFFSET)
#define GPIODIR_E_AHB *(volatile uint32_t *)(GPIODIR_E_AHB_BASE+GPIODIR_OFFSET)
#define GPIODIR_F_APB *(volatile uint32_t *)(GPIODIR_F_APB_BASE+GPIODIR_OFFSET)
#define GPIODIR_F_AHB *(volatile uint32_t *)(GPIODIR_F_AHB_BASE+GPIODIR_OFFSET)
	
		
